### ISSUE TITLE
Localized messages for Global module of Reports add-on are always shown in English

### ISSUE THREAD

**Issue by pfurini** [cuba-platform/translations#39]
I've tried everything on my side, but nothing seems to fix this..

Basically, if you include localized messages for the `Reports` add-on, they work BUT the `com.haulmont.reports.global` ones, even if they are correctly included and every property is translated. So, every entity name and related attributes are not translated, and they are shown in English.
I've checked that the `@include` directive was present in the `com.haulmont.reports.core` messages file, but it makes no difference if it is there or not.

The core CUBA `global` messages works well, and the system entities are properly translated, so it seems to be a problem with the add-on messages.

**Comment by jreznot** [comment]
Hi,
Could you share a sample project? It is hard to reproduce all the bug reports without seeing the actual problem with the context.

**Comment by pfurini** [comment]
Sure here it is: https://github.com/pfurini/cuba-test-reports-localization

The only available language is **Italian** and it has the `Reports` add-on included. If you start it, you'll notice that everything is in Italian, BUT the Reports' entity names and attributes (try for example to open the `Reports` screen, and notice that the column names are in English). On the other hand, if you open the `Users` screen for example, the entity names/attributes are correctly displayed in Italian.

**Comment by jreznot** [comment]
It seems that the location of messages_it.properties in reports global has changed

**Comment by jreznot** [comment]
I've changed the layout:
Moved messages_it.properties from com/haulmont/reports/global to com/haulmont/reports in global module

**Comment by jreznot** [comment]
@oshiryaeva Could you please check other locales in 6.9 ?

**Comment by pfurini** [comment]
Ok, I've rebased my PR #37 on the new commit, to avoid merge conflicts.. if you plan to accept it, please do it before doing other potentially conflicting commits on this branch, otherwise I'll have to rebase again ;)

Thx
P.
