### ISSUE TITLE
FTS add-on localization doesn't work

### ISSUE THREAD

**Issue by pfurini** [cuba-platform/translations#40]
Try to add a localized messages* file ubder the `modules/web/src/com/haulmont/fts/web` directory and you'll see the (few) messages from the FTS add-on will NOT be shown in the user's language (always in English).

Tested with Italian localization, but that shouldn't matter..

**Comment by natfirst** [comment]
As a workaround, add the path to the localisation: `com.haulmont.fts.web` to the `cuba.mainMessagePack` property in the` web-app.properties` file.

**Comment by pfurini** [comment]
Closing - it shouldn't be an issue anymore
