### ISSUE TITLE
release_6_10 branch contains old 6.8 Italian translations, and not 6.9 ones

### ISSUE THREAD

**Issue by pfurini** [cuba-platform/translations#43]
Hi
I realized only today that you probably based the `release_6_10` branch off the wrong branch.

In fact all my Italian messages come from this merge commit: `Add Italian translation for release 6.8 (#28)` and not from the one in the `release_6_9` branch.

Everyone that is using my IT translations in their 6.10 projects are effectively using the old messages for the 6.8 version!

Today I'm going to copy over the latest message files from the `release_6_9` branch, merge the new labels for 6.10 and open a PR against your `release_6_10` branch.
In the next few days I'll try to make and publish a new add-on containing my IT message files, to be used directly in target projects, as I see this method of maintaining translations too cumbersome and error prone.

P.

**UPDATE**: *Please check all the other translations*, because if you have branched from the wrong tip, other languages may be affected and not only mine

**Comment by pfurini** [comment]
**UPDATE 2**: Yes I can confirm that you branched off `release_6_8` instead of `release_6_9`, so all translations come from 6.8 and not 6.9 ...

![screen shot 2018-12-03 at 11 38 04](https://user-images.githubusercontent.com/4931051/49368790-f30afb80-f6ef-11e8-8eb6-d6fdb391b8ca.png)

**Comment by knstvk** [comment]
Hi Paolo
Thank you for finding the problem. It was a result of my local branching without pulling remote changes.
I've merged the 6.9 branch into 6.10, so now all your changes from 6.9 should be present.

**Comment by pfurini** [comment]
I see @knstvk .. the problem is that now all PRs pending on the `release_6_10` branch have conflicts.
Maybe send a comment to the contributors that they need to pull, rebase and then push new PRs.

P.

**Comment by knstvk** [comment]
You are right, will do.
