### ISSUE TITLE
About Simplified Chinese language 

### ISSUE THREAD

**Issue by GuoRuiLv** [cuba-platform/translations#46]
Hi, @knstvk !
We  will  translate all Chinese localization  messages.    I originally put the Chinese Simplified Message Pack in the zh-CN directory. Now we are considering moving it to the chs directory ，so that it matches the Chinese document directory name（chs).   
Do you have any suggestions about this?

**Comment by knstvk** [comment]
Hi @lugreen ,
What is the motivation for renaming the directory to `chs`? As far as I know, `zh-CN` is a correct abbreviation for Simplified Chinese. Could you elaborate?

**Comment by jingjingan** [comment]
Hi @knstvk ,
The original consideration is that we only provide 2 parent translations, one for Simplified and one for Traditional Chinese, as below MS did in .NET framework.
![image](https://user-images.githubusercontent.com/43785771/50409502-26900000-082e-11e9-8926-a011d4ddfbc9.png)

But after more discussion internally, also considering localization in different Chinese areas, we think you're right, and decided to abandon the idea of using `chs`. Maybe we can just focus on `zh_CN` for now. However curiously, why English version only have `en` and not `en_GB`/ `en_US`/`en_AU` as there are many countries speak different English?
