### ISSUE TITLE
Why not  provide language  package  using jar ?

### ISSUE THREAD

**Issue by GuoRuiLv** [cuba-platform/translations#55]
Hi, @knstvk 

If provide language package as jar file, then developer can add  a dependency in gradle build file  ，it's  convenient .
Or , Should we split messages for zh_CN to a independent project like  https://github.com/balvi/translation-de#translation-de  ?

Any sugeest?

**Comment by pfurini** [comment]
> Or , Should we split messages for zh_CN to a independent project like https://github.com/balvi/translation-de#translation-de ?

Hi, yes there are already two add-ons (app components) providing translations: the above one, and mine here: https://github.com/pfurini/cuba-translation-it

So the recommended approach so far has been to create language add-ons.

Paolo

**Comment by GuoRuiLv** [comment]
Hi, @pfurini ,thanks for your reply.
