### ISSUE TITLE
Change folders hierarchy for the French locale for the 7.1 CUBA platform version as in the English localization folders

### ISSUE THREAD

**Issue by MikhailSilk** [cuba-platform/translations#71]
Change folders hierarchy for the French locale for the 7.1 CUBA platform version as in the English localization folders
English localization:
![изображение](https://user-images.githubusercontent.com/24281695/89187830-d7d04d80-d5ae-11ea-90d4-6b3d47fef839.png)
French localization:
![изображение](https://user-images.githubusercontent.com/24281695/89188376-9e4c1200-d5af-11ea-8f63-eed9214e7459.png)
![изображение](https://user-images.githubusercontent.com/24281695/89187913-fa626680-d5ae-11ea-84df-5337521a4a54.png)
AR: Now `GUI` folder exists in the `modules` folder instead of `web/src/com/haulmont/cuba/` for the French locale for the 7.1 CUBA platform version

**Comment by knstvk** [comment]
Fixed in #72
