### ISSUE TITLE
Includes are not written to generated message pack when translation is made by mp2xls tool in accordance with manual

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/translations#8]
What is written in the "Full translation" documentation  here: https://github.com/cuba-platform/translations

1) Open the XLS file and add a new column for your language next to the default column. Give it a title denoting the language, for example zz.
2) Translate messages in this column into your language. Leave hidden rows which are marked red as they are

*What is the problem:* If to do as written - the values in hidden rows will not be copied to a new language column so, ''@include'' will not be added to generated message packs. User encountered the problem in the topic: https://www.cuba-platform.com/support/topic/which-directory-should-i-put-localization-message-pack
And reported it here: https://www.cuba-platform.com/support/topic/messages-file-not-have-the-include-directive-generated-by-mp2xls

![xlsmessages](https://cloud.githubusercontent.com/assets/19840141/24346199/704d41b2-12e4-11e7-968b-439814c5258f.png)

**Comment by knstvk** [comment]
Obsolete after moving to flat file structure in 6.6.
